### ISSUE TITLE
[Bug]: `cndi ow` does not properly communicate when string data is provided in `secret.data`

### ISSUE THREAD

**Issue by johnstonmatt** [polyseam/cndi#1080]
### What happened?

`cndi ow` threw 
```
error: Uncaught (in worker "") (in promise) InvalidCharacterError: Failed to decode base64
          const decodedSecretEnvVal = atob(secretEnvVal);
                                      ^
    at atob (ext:deno_web/05_base64.js:28:12)
    at parseCndiSecret (file:///Users/m/dev/polyseam/cndi/src/outputs/sealed-secret-manifest.ts:76:39)
    at getSealedSecretManifestWithKSC (file:///Users/m/dev/polyseam/cndi/src/outputs/sealed-secret-manifest.ts:247:39)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async self.onmessage (file:///Users/m/dev/polyseam/cndi/src/actions/overwrite.worker.ts:644:13)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
```
because the secret provided used Secret.data but the `.env` value to seal was a string instead of binary data

### Version

cndi v2.24.0
kubeseal v0.26.0
terraform v1.5.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnstonmatt** [comment]
fixed by #1084
